"""empty message

Revision ID: d70c6b1d1770
Revises: ef9a401c0e84
Create Date: 2025-10-14 18:19:53.145450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd70c6b1d1770'
down_revision = 'ef9a401c0e84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_index('ix_cart_item_product_id')
        batch_op.drop_constraint('cart_item_product_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.create_foreign_key('cart_item_product_id_fkey', 'product', ['product_id'], ['id'])
        batch_op.create_index('ix_cart_item_product_id', ['product_id'], unique=False)

    # ### end Alembic commands ###
